FROM ubuntu:22.04

LABEL author=HyperUser
LABEL "application_environment"="development"
LABEL "version"=1.0
LABEL multi.first-key="first-value" multi.second-key="second-value"
LABEL fist-key=fist-value \
      second-key=second-value

ENTRYPOINT ["/bin/bash"]
