version: '3.1'
services:
  mongodb:
    image: mongo:6.0.8
    container_name: hyper-mongo
    ports:
      - 27027:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - hyper-task-manager-network
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  hyper-task-manager-network:
